//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIPROYECTO2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public string idCliente { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string edad { get; set; }
        public string genero { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
    }
}
